name: Publish Nugets

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    env:
        BUILD_CONFIG: 'Release'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Bump versions
      uses: SiqiLu/dotnet-bump-version@2.0.0
      with:
        version_files: "**/VpnHood.Client.App.Android.Ads.UnityAds.csproj"
        version_mask: 0.0.1.0
        version_overwrite: "*.*.*.*"
        github_token: ${{ secrets.GITHUB_TOKEN }}
   
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Android SDK
      run: dotnet workload install android

    - name: Restore dependencies
      run: dotnet restore VpnHood.Client.App.Android.Ads.UnityAds

    - name: Build Solution
      run: dotnet build VpnHood.Client.App.Android.Ads.UnityAds --no-restore --configuration $BUILD_CONFIG

    - name: Pack All Projects
      run: dotnet pack VpnHood.Client.App.Android.Ads.UnityAds --configuration $BUILD_CONFIG -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg

    - name: Publish
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
